"""Chunks Schema added

Revision ID: 466d82bf3c92
Revises: bf218b260b3b
Create Date: 2025-10-25 20:31:45.816588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466d82bf3c92'
down_revision: Union[str, Sequence[str], None] = 'bf218b260b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.String(), nullable=True),
    sa.Column('end_char', sa.String(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('chunking_strategy', sa.String(), nullable=True))
    op.drop_column('documents', 'embedding_id')
    op.add_column('embedding_jobs', sa.Column('chunk_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'embedding_jobs', 'chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embedding_jobs', type_='foreignkey')
    op.drop_column('embedding_jobs', 'chunk_id')
    op.add_column('documents', sa.Column('embedding_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'chunking_strategy')
    op.drop_table('chunks')
    # ### end Alembic commands ###
